In [1]:

import os
import pandas as pd 
import matplotlib.pyplot as plot 
import numpy as np

In [3]:
#reading CSV file into DataFrame 

dataset1 = pd.read_csv('Dataset1.csv') 

pd.set_option('display.max_columns', None)

dataset1.head(5)

,patient_id,date_of_birth,medical_condition,co_morbidity,ethnicity,risk_factor,lmp,cycle_length,edd,number_of_babies,other checks,infection_history,past_medical_history,pastPregnancy,medications
0,6,30/01/1990,POSTPARTUM,diabetes,Mixed,LOW,01/06/2022,28,08/03/2023,1,NaN,NaN,diabetes,para=>1living=>1gravida=>1ectopics=>has_risk=>...,dose=>1name=>aspirin 81 MG Delayed Release Ora...
1,7,22/10/1986,POSTPARTUM,obesity,Non Hispanic White,LOW,13/07/2021,28,19/04/2022,1,RHNegative,"hep_b,chicken_pox","Covid,obesity,drug_allergy_list,advanced_mater...",para=>3living=>3gravida=>4ectopics=>has_risk=>...,dose=>81name=>aspirin 81 MG Delayed Release Or...
2,8,05/07/1982,PREGNANCY,obesity,Hispanic and Latino,MEDIUM,23/07/2021,28,29/04/2022,1,NaN,"gen_herp,chicken_pox","obesity,diabetes,hepatitis_liver_disease,histo...",para=>0living=>gravida=>1ectopics=>has_risk=>Y...,dose=>5mgname=>glyburide 5 MG / metformin hydr...
3,9,06/12/1983,PREGNANCY,NaN,Non Hispanic White,LOW,20/10/2021,28,27/07/2022,1,chk_ntd,NaN,"diabetes,allergies,psychiatric,drug_allergy_list",para=>0living=>gravida=>2ectopics=>has_risk=>Y...,"dose=>5 unitsname=>3 ML insulin isophane, huma..."
4,13,16/03/1996,POSTPARTUM,obesity,Hispanic and Latino,MEDIUM,30/09/2021,28,07/07/2022,1,NaN,chicken_pox,obesity,para=>1living=>1gravida=>1ectopics=>has_risk=>...,dose=>1name=>aspirin 81 MG Delayed Release Ora...

In [4]:

# splitting the column 'pastPregnancy' by > and storing it in a new dataframe

temp = dataset1['pastPregnancy'].str.split('>', expand=True)

# renaming required columns from index values

temp = temp.rename(columns={temp.columns[1]: 'A'})
temp = temp.rename(columns={temp.columns[2]: 'B'})
temp = temp.rename(columns={temp.columns[3]: 'C'})

# separating first character in the columns

temp['para'] = temp['A'].str[:1]
temp['living'] = temp['B'].str[:1]
temp['gravida'] = temp['C'].str[:1]

# cleaning the data

temp['para'] = temp['para'].str.replace('l','0')
temp['living'] = temp['living'].str.replace('g','0')
temp['gravida'] = temp['gravida'].str.replace('e','0')

# converting object type columns to integer type

temp['para'] = temp['para'].astype(str).astype(int)
temp['gravida'] = temp['gravida'].astype(str).astype(int)
temp['living'] = temp['living'].astype(str).astype(int)

# calculating gravida-para

dataset1['previous_unsuccessful_pregnancies'] = temp['gravida'] - temp['para']

In [5]:
# reading the dataframe into csv

dataset1.to_csv(r'dataset1test.csv')

# Merging  Datasets

In [91]:
df2 = pd.read_csv("Dataset2.csv")

df2.head()

,patient_id,appointment_type,appointment_status,doctor_advice_notes,clinical_observations,diagnosis_title,appointment_reason,start_time,end_time
0,7,virtual,completed,Client discharged weeks ago. Had healthy baby ...,Discharged. Had healthy baby girl,Adhoc Consult,Ad Hoc Consult,27/04/2022 18:00,27/04/2022 18:15
1,8,virtual,completed,"Told her to eat a light snack at bedtime, 1/2 ...",Patient says her BS a little low in morning wh...,"weight, Blood sugars at 09:00 am Apr 05, 2022","weight, Blood sugars",05/04/2022 13:00,05/04/2022 13:15
2,8,virtual,completed,On last visit I had suggested patient eat a li...,Patient says trying to eat healthy. Checking b...,"weight, Blood sugars at 09:00 am Apr 12, 2022","weight, Blood sugars",12/04/2022 13:00,12/04/2022 13:15
3,8,virtual,completed,"Continue with same diet, drinking fluids esp. ...",Client called on phone unable to connect was i...,"weight, Blood sugars at 09:00 am Apr 19, 2022","weight, Blood sugars",19/04/2022 13:00,19/04/2022 13:15
4,8,virtual,completed,call me if any problems,patient doing well BS 68. No problems.,Adhoc Consult,Ad Hoc Consult,22/03/2022 13:00,22/03/2022 13:15

In [92]:
df3 = pd.read_csv("Dataset3.csv",header=None)
col_names =["patient_id","appointment_type","appointment_status","clinical_observations_1","diagnosis_title","appointment_reason_1","start_time","end_time","info"]
df3.columns = col_names
df3.head()

,patient_id,appointment_type,appointment_status,clinical_observations_1,diagnosis_title,appointment_reason_1,start_time,end_time,info
0,7,virtual,expired,NaN,NaN,f/u with wt and doppler,11/03/2022 15:30,11/03/2022 16:00,NaN
1,7,virtual,expired,NaN,NaN,follow up,14/03/2022 13:00,14/03/2022 13:15,NaN
2,7,clinic,inprogress,NaN,NaN,Ad Hoc Consult,15/03/2022 12:29,15/03/2022 12:44,NaN
3,7,virtual,completed,NaN,Adhoc Consult,Ad Hoc Consult,16/03/2022 17:45,16/03/2022 18:00,NaN
4,7,virtual,expired,NaN,NaN,weight,21/03/2022 13:30,21/03/2022 13:45,NaN

In [93]:
df2= df2.drop(["appointment_type","appointment_status","diagnosis_title","start_time","end_time"],axis=1)

df2.head()

,patient_id,doctor_advice_notes,clinical_observations,appointment_reason
0,7,Client discharged weeks ago. Had healthy baby ...,Discharged. Had healthy baby girl,Ad Hoc Consult
1,8,"Told her to eat a light snack at bedtime, 1/2 ...",Patient says her BS a little low in morning wh...,"weight, Blood sugars"
2,8,On last visit I had suggested patient eat a li...,Patient says trying to eat healthy. Checking b...,"weight, Blood sugars"
3,8,"Continue with same diet, drinking fluids esp. ...",Client called on phone unable to connect was i...,"weight, Blood sugars"
4,8,call me if any problems,patient doing well BS 68. No problems.,Ad Hoc Consult

In [94]:
df3= df3.drop(["appointment_type","appointment_status","diagnosis_title","start_time","end_time"],axis=1)
df3.head()

   patient_id clinical_observations_1     appointment_reason_1 info
0           7                     NaN  f/u with wt and doppler  NaN
1           7                     NaN                follow up  NaN
2           7                     NaN           Ad Hoc Consult  NaN
3           7                     NaN           Ad Hoc Consult  NaN
4           7                     NaN                   weight  NaN

In [95]:
def concat_values(series):
    return ','.join(str(x) for x in series)

df2 = df2.groupby('patient_id')[['doctor_advice_notes', 'clinical_observations','appointment_reason']].agg(concat_values).reset_index()
df2.head()

,patient_id,doctor_advice_notes,clinical_observations,appointment_reason
0,7,Client discharged weeks ago. Had healthy baby ...,Discharged. Had healthy baby girl,Ad Hoc Consult
1,8,"Told her to eat a light snack at bedtime, 1/2 ...",Patient says her BS a little low in morning wh...,"weight, Blood sugars,weight, Blood sugars,weig..."
2,13,"Encouraging to watch diet,nan,Enc her to eat o...","Blood glucose 110. Patient without problems.,n...","weight,weight,weight,weight,weight,weight,weig..."
3,14,Enc to drink plenty of fluids to assist with m...,Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question..."
4,15,"Encouraged client to watch sodium intake, drin...",Patients BP elevated from yesterday. 123/84 3/...,"blood pressure check & weight,blood pressure c..."

In [96]:
df3 = df3.groupby('patient_id')[[ 'clinical_observations_1','appointment_reason_1','info']].agg(concat_values).reset_index()

df3.head()

,patient_id,clinical_observations_1,appointment_reason_1,info
0,7,"nan,nan,nan,nan,nan,nan,Discharged. Had health...","f/u with wt and doppler,follow up,Ad Hoc Consu...","nan,nan,nan,nan,nan,nan,nan"
1,8,"nan,nan,nan,Patient says her BS a little low i...","Glucose monitoring, weight,weight, Blood sugar...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na..."
2,11,"nan,nan,nan,nan,nan,observations entered by CM...","Follow-up consult,admin books,Ad Hoc Consult,t...","nan,nan,edema=>+1,cervix_exam=>EFF,fundal_heig..."
3,12,"nan,nan,nan,nan,nan,nan,nan,nan,nan","CM interaction_1,CM interaction_2,Ad Hoc Consu...","nan,nan,nan,nan,nan,nan,edema=>0,cervix_exam=>..."
4,13,"nan,Blood glucose 110. Patient without problem...","weight checks,weight,weight,weight,weight,weig...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na..."

In [97]:
df_merged = pd.merge(df2, df3, on='patient_id')
df_merged.head()

,patient_id,doctor_advice_notes,clinical_observations,appointment_reason,clinical_observations_1,appointment_reason_1,info
0,7,Client discharged weeks ago. Had healthy baby ...,Discharged. Had healthy baby girl,Ad Hoc Consult,"nan,nan,nan,nan,nan,nan,Discharged. Had health...","f/u with wt and doppler,follow up,Ad Hoc Consu...","nan,nan,nan,nan,nan,nan,nan"
1,8,"Told her to eat a light snack at bedtime, 1/2 ...",Patient says her BS a little low in morning wh...,"weight, Blood sugars,weight, Blood sugars,weig...","nan,nan,nan,Patient says her BS a little low i...","Glucose monitoring, weight,weight, Blood sugar...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na..."
2,13,"Encouraging to watch diet,nan,Enc her to eat o...","Blood glucose 110. Patient without problems.,n...","weight,weight,weight,weight,weight,weight,weig...","nan,Blood glucose 110. Patient without problem...","weight checks,weight,weight,weight,weight,weig...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na..."
3,14,Enc to drink plenty of fluids to assist with m...,Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question...",Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na..."
4,15,"Encouraged client to watch sodium intake, drin...",Patients BP elevated from yesterday. 123/84 3/...,"blood pressure check & weight,blood pressure c...","nan,Patients BP elevated from yesterday. 123/8...","blood pressure check & weight,blood pressure c...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan"

In [98]:
df_merged["full_clinical_obs"] =  df_merged['clinical_observations']+df_merged['clinical_observations_1']
df_merged["full_Appointment_reasons"] =  df_merged['appointment_reason']+df_merged['appointment_reason_1']
df_merged = df_merged.drop(["clinical_observations","clinical_observations_1","appointment_reason","appointment_reason_1"],axis=1)
df_merged.head()

,patient_id,doctor_advice_notes,info,full_clinical_obs,full_Appointment_reasons
0,7,Client discharged weeks ago. Had healthy baby ...,"nan,nan,nan,nan,nan,nan,nan","Discharged. Had healthy baby girlnan,nan,nan,n...","Ad Hoc Consultf/u with wt and doppler,follow u..."
1,8,"Told her to eat a light snack at bedtime, 1/2 ...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient says her BS a little low in morning wh...,"weight, Blood sugars,weight, Blood sugars,weig..."
2,13,"Encouraging to watch diet,nan,Enc her to eat o...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...","Blood glucose 110. Patient without problems.,n...","weight,weight,weight,weight,weight,weight,weig..."
3,14,Enc to drink plenty of fluids to assist with m...,"nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question..."
4,15,"Encouraged client to watch sodium intake, drin...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan",Patients BP elevated from yesterday. 123/84 3/...,"blood pressure check & weight,blood pressure c..."

In [99]:
df =  pd.merge(dataset1,df_merged, on="patient_id")
df.head()

,patient_id,date_of_birth,medical_condition,co_morbidity,ethnicity,risk_factor,lmp,cycle_length,edd,number_of_babies,other checks,infection_history,past_medical_history,pastPregnancy,medications,previous_unsuccessful_pregnancies,doctor_advice_notes,info,full_clinical_obs,full_Appointment_reasons
0,7,22/10/1986,POSTPARTUM,obesity,Non Hispanic White,LOW,13/07/2021,28,19/04/2022,1,RHNegative,"hep_b,chicken_pox","Covid,obesity,drug_allergy_list,advanced_mater...",para=>3living=>3gravida=>4ectopics=>has_risk=>...,dose=>81name=>aspirin 81 MG Delayed Release Or...,1,Client discharged weeks ago. Had healthy baby ...,"nan,nan,nan,nan,nan,nan,nan","Discharged. Had healthy baby girlnan,nan,nan,n...","Ad Hoc Consultf/u with wt and doppler,follow u..."
1,8,05/07/1982,PREGNANCY,obesity,Hispanic and Latino,MEDIUM,23/07/2021,28,29/04/2022,1,NaN,"gen_herp,chicken_pox","obesity,diabetes,hepatitis_liver_disease,histo...",para=>0living=>gravida=>1ectopics=>has_risk=>Y...,dose=>5mgname=>glyburide 5 MG / metformin hydr...,1,"Told her to eat a light snack at bedtime, 1/2 ...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient says her BS a little low in morning wh...,"weight, Blood sugars,weight, Blood sugars,weig..."
2,13,16/03/1996,POSTPARTUM,obesity,Hispanic and Latino,MEDIUM,30/09/2021,28,07/07/2022,1,NaN,chicken_pox,obesity,para=>1living=>1gravida=>1ectopics=>has_risk=>...,dose=>1name=>aspirin 81 MG Delayed Release Ora...,0,"Encouraging to watch diet,nan,Enc her to eat o...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...","Blood glucose 110. Patient without problems.,n...","weight,weight,weight,weight,weight,weight,weig..."
3,14,09/02/1984,POSTPARTUM,obesity,Black or African,MEDIUM,08/12/2021,28,14/09/2022,1,NaN,"chicken_pox,history_std","obesity,hypertension,history_of_abnormal_pap",para=>4living=>4gravida=>5ectopics=>has_risk=>...,dose=>1name=>labetalol hydrochloride 100 MG Or...,1,Enc to drink plenty of fluids to assist with m...,"nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question..."
4,15,10/02/1990,PREGNANCY,obesity,Hispanic and Latino,MEDIUM,31/07/2021,28,07/05/2022,1,NaN,chicken_pox,obesity,para=>1living=>gravida=>1ectopics=>has_risk=>Y...,NaN,0,"Encouraged client to watch sodium intake, drin...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan",Patients BP elevated from yesterday. 123/84 3/...,"blood pressure check & weight,blood pressure c..."

In [104]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='%d/%m/%Y')
df['edd'] = pd.to_datetime(df['edd'], format='%d/%m/%Y')

In [106]:
years, months = divmod((df['edd'] - df['date_of_birth']).dt.days, 365)
df['Age_at_pregnancy'] = years.round()
df.head()

,patient_id,date_of_birth,medical_condition,co_morbidity,ethnicity,risk_factor,lmp,cycle_length,edd,number_of_babies,other checks,infection_history,past_medical_history,pastPregnancy,medications,previous_unsuccessful_pregnancies,doctor_advice_notes,info,full_clinical_obs,full_Appointment_reasons,Age_at_pregnancy
0,7,1986-10-22,POSTPARTUM,obesity,Non Hispanic White,LOW,13/07/2021,28,2022-04-19,1,RHNegative,"hep_b,chicken_pox","Covid,obesity,drug_allergy_list,advanced_mater...",para=>3living=>3gravida=>4ectopics=>has_risk=>...,dose=>81name=>aspirin 81 MG Delayed Release Or...,1,Client discharged weeks ago. Had healthy baby ...,"nan,nan,nan,nan,nan,nan,nan","Discharged. Had healthy baby girlnan,nan,nan,n...","Ad Hoc Consultf/u with wt and doppler,follow u...",35
1,8,1982-07-05,PREGNANCY,obesity,Hispanic and Latino,MEDIUM,23/07/2021,28,2022-04-29,1,NaN,"gen_herp,chicken_pox","obesity,diabetes,hepatitis_liver_disease,histo...",para=>0living=>gravida=>1ectopics=>has_risk=>Y...,dose=>5mgname=>glyburide 5 MG / metformin hydr...,1,"Told her to eat a light snack at bedtime, 1/2 ...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient says her BS a little low in morning wh...,"weight, Blood sugars,weight, Blood sugars,weig...",39
2,13,1996-03-16,POSTPARTUM,obesity,Hispanic and Latino,MEDIUM,30/09/2021,28,2022-07-07,1,NaN,chicken_pox,obesity,para=>1living=>1gravida=>1ectopics=>has_risk=>...,dose=>1name=>aspirin 81 MG Delayed Release Ora...,0,"Encouraging to watch diet,nan,Enc her to eat o...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...","Blood glucose 110. Patient without problems.,n...","weight,weight,weight,weight,weight,weight,weig...",26
3,14,1984-02-09,POSTPARTUM,obesity,Black or African,MEDIUM,08/12/2021,28,2022-09-14,1,NaN,"chicken_pox,history_std","obesity,hypertension,history_of_abnormal_pap",para=>4living=>4gravida=>5ectopics=>has_risk=>...,dose=>1name=>labetalol hydrochloride 100 MG Or...,1,Enc to drink plenty of fluids to assist with m...,"nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,na...",Patient looks well. BP WNL 119/70. Weight sta...,"weight management, BP monitoring, med question...",38
4,15,1990-02-10,PREGNANCY,obesity,Hispanic and Latino,MEDIUM,31/07/2021,28,2022-05-07,1,NaN,chicken_pox,obesity,para=>1living=>gravida=>1ectopics=>has_risk=>Y...,NaN,0,"Encouraged client to watch sodium intake, drin...","nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan",Patients BP elevated from yesterday. 123/84 3/...,"blood pressure check & weight,blood pressure c...",32

In [ ]:
##df.to_csv(r'final_dataset.csv')